### ISSUE TITLE
Using Ubuntu 22.04 as base

### ISSUE THREAD

**Issue by mwllgr** [restreamio/docker-gstreamer#13]
Hi, trying to compile something written in Rust using your images. However, I need libnice in a newer version which only seems to be included in Ubuntu 22.04 by default.

`Requested 'nice >= 0.1.18' but version of libnice is 0.1.16`

Is there an easy way to use Ubuntu 22.04 as base image?

**Comment by amirjalali1** [comment]
The current base image is no longer supported, so I agree that it would be ideal if the Ubuntu base image used an LTS version.
