### ISSUE TITLE
Trouble finding vanilla images on Dockerhub

### ISSUE THREAD

**Issue by cameronelliott** [restreamio/docker-gstreamer#3]
Thank you, thank you very much for creating this. This really fills an important void.

I'm sorry I don't understand the naming convention for the vanilla builds.

Just to be clear, if the gstreamer version number is included in the tag, then that is a vanilla build
without restreamer patches??

Do I understand correctly from the table?
Thank you, Cameron

```
docker pull restreamio/gstreamer:1.18.4.0-dev-with-source    # vanilla WITHOUT Restream-specific patches ??
docker pull restreamio/gstreamer:2021-03-22T07-07-28Z-prod     # With Restream-specific patches ??
```

**Comment by nazar-pc** [comment]
Yes, you are 100% correct.
