### ISSUE TITLE
Trying to use restreamio/gstreamer:x86_64-latest-prod with cef plugin but it is not present

### ISSUE THREAD

**Issue by iongion** [restreamio/docker-gstreamer#38]
With the dev build,  I see it compiles and gets it locally, am I missing something ?
Big thank you for all this effort!

**Comment by philn** [comment]
you need to add `/usr/cef/` (iirc) to the `GST_PLUGIN_PATH` env var.

**Comment by ArmorDarks** [comment]
Looks like it's the way to go. Closing for now.
