### ISSUE TITLE
Does it include webrtcsink / webrtcsrc from gst-plugins-rs ?

### ISSUE THREAD

**Issue by fabito** [restreamio/docker-gstreamer#51]
https://gstreamer.freedesktop.org/documentation/rswebrtc/webrtcsink.html?gi-language=c#webrtcsink-and-webrtcsrc

**Comment by pyldin601** [comment]
AFAIK, nope.

It had it in previous builds, but today I don't see `gst-plugins-rs` in dependencies.

**Comment by neodesys** [comment]
This image only includes the plugins from the GStreamer mono-repo. It is not planned to add gst-plugins-rs for the moment but you can easily add them to your container taking the prod or prod-dbg image as a base.
